#!/bin/bash
if [ "$EUID" -ne 0 ]
then 
	printf "Please run as root"
	exit
else
	echo -e '\e[1;33m==Haciendo update===\e[0m'
        apt-get update -y
        echo -e '\e[1;33m===Haciendo upgrade===\e[0m'
        apt-get upgrade -y
        echo -e '\e[1;33m===Actualizando firmware===\e[0m'
        rpi-update -y
        echo -e '\e[1;33mTodo listo, vamos a reiniciar\e[0m'
        sleep 10s
fi
